services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: es
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    environment:
      - node.name=es
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ=Asia/Shanghai
    mem_limit: 2g
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    depends_on:
      es:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.17.4
    container_name: kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
      - xpack.security.enabled=false
      - xpack.reporting.roles.enabled=false
      - TZ=Asia/Shanghai
    mem_limit: 1g
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'", ]
      interval: 10s
      timeout: 10s
      retries: 120

  # filebeat:
  #   build: ./filebeat
  #   container_name: filebeat
  #   user: root
  #   volumes:
  #   - ./data/nginx:/var/log/nginx:ro

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
