services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es
      - cluster.name=${CLUSTER_NAME}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - TZ=Asia/Shanghai
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 | grep -q 'You Know, for Search'"]
      interval: 10s
      timeout: 10s
      retries: 10

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es:9200
      # - I18N_LOCALE=zh-CN
      - xpack.security.enabled=false
      - xpack.reporting.roles.enabled=false
      - TZ=Asia/Shanghai
    depends_on:
      es:
        condition: service_healthy
    mem_limit: ${MEM_LIMIT}
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'", ]
      interval: 10s
      timeout: 10s
      retries: 120

  filebeat:
    build: ./filebeat
    container_name: filebeat
    user: root
    volumes:
    - ./data/nginx:/var/log/nginx:ro

volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
