filebeat.modules:
  - module: nginx
    access:
      enabled: true
      var.paths: ["/var/log/nginx/access.log"]
      input: filestream

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'

# filebeat.autodiscover:
#   providers:
#     - type: docker
#       hints.enabled: true

# output.kafka:
#   # initial brokers for reading cluster metadata
#   hosts: ["broker:19092"]
#   # message topic selection + partitioning
#   topic: 'nginx-logs'
#   partition.round_robin:
#     reachable_only: false
#   required_acks: 1
#   compression: gzip
#   max_message_bytes: 1000000
